# Generated by Django 3.2.4 on 2021-06-17 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='pissengers',
            field=models.IntegerField(),
        ),
    ]
